# _config.yml
title: Logan Sheltons portfolio
description: Showcases Logan Shelton's Live Service Build Engineering work over the years
theme: jekyll-remote-theme
remote_theme: pages-themes/hacker@v0.2.0